---
title: "Group 9 Project"
number-sections: true
format: 
  html:
    embed-resources: true
    code-tools: true
editor_options: 
  chunk_output_type: console
theme: flatly
---

# Introduction {#sec-intro}

The 2008 - 2012 Scottish Health Survey provides key insight into the health trends of Scottish residents. It provides information on *age*, *sex*, *employment status*, and *BMI* of people, sorted by the year the survey data was collected. The following report seeks to explore the relationship of obesity over time, exploring whether or not the prevalence of obesity is changing. The report also seeks to explore whether or not there any differences in obesity by age, gender, socio-economic status or lifestyle factors.

@sec-eda consists of an exploratory analysis of the Survey data and explores the potential relationship between obesity and time, and whether there are any differences in obesity by other factors. @sec-fda contains the results from fitting a multiple regression model to the data, as well as the assessment of the model assumptions. Concluding remarks are given in @sec-conc.

# Exploratory Data Analysis {#sec-eda}

# Formal Data Analysis {#sec-fda}

# Conclusions {#sec-conc}
