---
title: "Group 9 Project"
number-sections: true
format: 
  html:
    embed-resources: true
    code-tools: true
editor_options: 
  chunk_output_type: console
theme: flatly
---

```{r}
#| echo: false
#| warning: false
#| message: false
library(ggplot2)
library(tidyverse)
library(sjPlot)
library(performance)
library(kableExtra)
#this is the name given to the .csv file. If anyone is making plots, use data=DAProject9
DAProject9 <- read.csv("DAProject9.csv")
```


# Introduction {#sec-intro}

The 2008 - 2012 Scottish Health Survey provides key insight into the health trends of Scottish residents. It provides information on *age*, *sex*, *employment status*, and *BMI* of people, sorted by the year the survey data was collected. The following report seeks to explore the relationship of obesity over time, exploring whether or not the prevalence of obesity is changing. The report also seeks to explore whether or not there any differences in obesity by age, gender, socio-economic status or lifestyle factors.

@sec-eda consists of an exploratory analysis of the Survey data and explores the potential relationship between obesity and time, and whether there are any differences in obesity by other factors. @sec-fda contains the results from fitting a multiple regression model to the data, as well as the assessment of the model assumptions. Concluding remarks are given in @sec-conc.

# Exploratory Data Analysis {#sec-eda}

# Formal Data Analysis {#sec-fda}

# Conclusions {#sec-conc}

Analysis showed no relationship between the probability of obesity and time, suggesting that there has been *no change* in the **prevalence** of obesity in Scotland over the period of the study. However, we did find differences in obesity by some of our other variables. Namely, **age** and **employment status** were shown to relate to probability of obesity.

Our analysis suggests that one's probability of obesity *increases* into middle adulthood and peaks at the **55-64** and **65-74** groups before *declining* for those in the **75+** group. Those in **full-time education** had significantly *lower* odds than the baseline category, while those who are **permanently unable to work** had *higher* odds. All other employment status categories were *not* found to be significant. The individuals' **sex** was found to have *no effect* with probability of obesity.

This study provides great framework for understanding obesity in our population and can be used as a platform for future research. Recording additional lifestyle factors in future surveys, as well monitoring obesity trends over a larger period of time, will help to further our understanding of the issue.
